Repository Amsterdam/amsterdam-styled-components, pull requests merged in 2020-11, with the labels that each got.

#1299 Fixed the Modal component `zIndexOffset` prop warning
  packages/asc-ui/src/components/Focus/Focus.tsx
Labels: maintenance

#1256 bug/ASC-634-IE11-bug-TAG-component
  CHANGELOG.md
  packages/asc-ui/src/components/Tag/TagStyle.ts
Labels: Internet Explorer, bug

#1296 Added background color to the Button focus state
  CHANGELOG.md
  packages/asc-ui/src/components/Button/ButtonStyle.ts
Labels: enhancement

#1295 Updated variants/levels for Alert component
  CHANGELOG.md
  packages/asc-ui/src/components/Alert/Alert.tsx
  packages/asc-ui/src/components/Alert/AlertStyle.ts
  stories/src/ui/Alert.stories.mdx
Labels: design-system-alignment

#1322 Upgrade typescript-eslint to latest version and fix linting issues
  .eslintrc.js
  package.json
  packages/asc-ui/.eslintrc.js
  packages/asc-ui/src/components/Button/ShareButton/ShareButton.test.tsx
  packages/asc-ui/src/components/Card/CardActions.tsx
  packages/asc-ui/src/components/Card/CardContent.tsx
  packages/asc-ui/src/components/Checkbox/Checkbox.test.tsx
  packages/asc-ui/src/components/ContextMenu/ContextMenuList.tsx
  packages/asc-ui/src/components/DocumentCover/DocumentCoverContent/DocumentCoverContent.tsx
  packages/asc-ui/src/components/DocumentCover/DocumentCoverStyle.ts
  packages/asc-ui/src/components/Editorial/Article/ArticleStyle.ts
  packages/asc-ui/src/components/Editorial/EditorialBody/EditorialBody.tsx
  packages/asc-ui/src/components/Editorial/EditorialBody/EditorialBodyStyle.ts
  packages/asc-ui/src/components/FilterBox/FilterBox.tsx
  packages/asc-ui/src/components/FilterBox/FilterBoxStyle.ts
  packages/asc-ui/src/components/FilterTag/FilterTag.tsx
  packages/asc-ui/src/components/Focus/Focus.tsx
  packages/asc-ui/src/components/Footer/Footer.tsx
  packages/asc-ui/src/components/Grid/ContainerStyle.ts
  packages/asc-ui/src/components/Header/HeaderNavigation.tsx
  packages/asc-ui/src/components/Label/LabelContext.ts
  packages/asc-ui/src/components/List/ListItemStyle.ts
  packages/asc-ui/src/components/Menu/MenuContext.ts
  packages/asc-ui/src/components/Menu/MenuFlyOut/MenuFlyOut.test.tsx
  packages/asc-ui/src/components/Menu/MenuInline/MenuInlineStyle.ts
  packages/asc-ui/src/components/Menu/MenuItemTitle/MenuItemTitle.tsx
  packages/asc-ui/src/components/Menu/MenuToggle/MenuToggleStyle.ts
  packages/asc-ui/src/components/Modal/Modal.tsx
  packages/asc-ui/src/components/Modal/ModalStyle.ts
  packages/asc-ui/src/components/Portal/Portal.tsx
  packages/asc-ui/src/components/Radio/Radio.tsx
  packages/asc-ui/src/components/Radio/RadioContext.ts
  packages/asc-ui/src/components/Radio/RadioStyle.ts
  packages/asc-ui/src/components/SearchBar/SearchBar.test.tsx
  packages/asc-ui/src/components/SearchBar/SearchBarStyle.ts
  packages/asc-ui/src/components/SearchBarToggle/SearchBarToggle.tsx
  packages/asc-ui/src/components/Select/Select.test.tsx
  packages/asc-ui/src/components/Select/SelectStyle.ts
  packages/asc-ui/src/components/Tabs/Tabs.tsx
  packages/asc-ui/src/components/TextField/TextField.tsx
  packages/asc-ui/src/components/Toggle/Toggle.test.tsx
  packages/asc-ui/src/components/Toggle/Toggle.tsx
  packages/asc-ui/src/types/Theme.ts
  packages/asc-ui/src/utils/deprecatedWarning.ts
  packages/asc-ui/src/utils/hooks/useActionOnEscape.ts
  packages/asc-ui/src/utils/hooks/useDebounce.ts
  packages/asc-ui/src/utils/hooks/useOptionalControlledState.test.tsx
  packages/asc-ui/src/utils/hooks/useOptionalControlledState.ts
  packages/asc-ui/src/utils/hooks/usePassPropsToChildren.ts
  packages/asc-ui/src/utils/ownerDocument.ts
  packages/asc-ui/src/utils/themeUtils.ts
  stories/src/ui/ReactTableExample.tsx
  yarn.lock
Labels: dependencies, enhancement

#1334 Export Alert component types from package root
  CHANGELOG.md
  packages/asc-ui/src/components/Alert/Alert.tsx
  packages/asc-ui/src/components/Alert/AlertStyle.ts
  packages/asc-ui/src/components/Alert/index.ts
  packages/asc-ui/src/index.ts
Labels: enhancement, typescript
