Repository Amsterdam/amsterdam-styled-components, pull requests merged in 2020-07, with the labels that each got.

#771 Use createEvent utility to support older browsers
  CHANGELOG.md
  packages/asc-ui/src/components/Select/Select.tsx
  packages/asc-ui/src/utils/createEvent.ts
Labels: bug

#783 Fix link to fonts documentation
  docs/GETTING_STARTED.md
Labels: bug, documentation

#876 Fix: The Select component with the `disabled` prop had an issue with background-color
  CHANGELOG.md
  packages/asc-ui/src/components/Select/SelectStyle.ts
Labels: bug

#896 Refactor focus styling utilities and export them
  CHANGELOG.md
  packages/asc-ui/src/components/Alert/AlertStyle.ts
  packages/asc-ui/src/components/AmsterdamLogo/AmsterdamLogoStyle.ts
  packages/asc-ui/src/components/Button/ButtonStyle.ts
  packages/asc-ui/src/components/Checkbox/CheckboxStyle.ts
  packages/asc-ui/src/components/ContextMenu/ContextMenuButtonStyle.ts
  packages/asc-ui/src/components/FilterOption/FilterOptionStyle.ts
  packages/asc-ui/src/components/Input/InputStyle.ts
  packages/asc-ui/src/components/Link/LinkStyle.ts
  packages/asc-ui/src/components/Radio/RadioStyle.ts
  packages/asc-ui/src/components/Select/SelectStyle.ts
  packages/asc-ui/src/index.ts
  packages/asc-ui/src/utils/__tests__/themeUtils.test.tsx
  packages/asc-ui/src/utils/focus.ts
  packages/asc-ui/src/utils/index.ts
  packages/asc-ui/src/utils/themeUtils.ts
Labels: enhancement

#906 Add focus outline to links in CustomHTMLBlock
  packages/asc-ui/src/components/CustomHTMLBlock/CustomHTMLBlockStyle.ts
Labels: accessibility, bug
