Repository Amsterdam/amsterdam-styled-components, pull requests merged in 2020-08, with the labels that each got.

#941 Extend CompactThemeProvider with same props as ThemeProvider
  CHANGELOG.md
  packages/asc-ui/src/theme/CompactThemeProvider.tsx
  packages/asc-ui/src/theme/ThemeProvider.tsx
  yarn.lock
Labels: enhancement

#943 Removed custom focus styles, now use browser native focus
  CHANGELOG.md
  packages/asc-ui/src/components/Alert/AlertStyle.ts
  packages/asc-ui/src/components/AmsterdamLogo/AmsterdamLogoStyle.ts
  packages/asc-ui/src/components/Button/ButtonStyle.ts
  packages/asc-ui/src/components/Checkbox/Checkbox.tsx
  packages/asc-ui/src/components/Checkbox/CheckboxStyle.ts
  packages/asc-ui/src/components/ContextMenu/ContextMenuButtonStyle.ts
  packages/asc-ui/src/components/CustomHTMLBlock/CustomHTMLBlockStyle.ts
  packages/asc-ui/src/components/FilterOption/FilterOptionStyle.ts
  packages/asc-ui/src/components/FilterTag/FilterTag.tsx
  packages/asc-ui/src/components/FilterTag/FilterTagStyle.ts
  packages/asc-ui/src/components/GlobalStyle/GlobalStyle.ts
  packages/asc-ui/src/components/Input/InputStyle.ts
  packages/asc-ui/src/components/Link/LinkStyle.ts
  packages/asc-ui/src/components/Radio/Radio.test.tsx
  packages/asc-ui/src/components/Radio/RadioStyle.ts
  packages/asc-ui/src/components/Select/SelectStyle.ts
  packages/asc-ui/src/components/Tag/Tag.tsx
  packages/asc-ui/src/components/Tag/TagStyle.ts
  packages/asc-ui/src/index.ts
  packages/asc-ui/src/utils/focus.ts
Labels: design-system-alignment, enhancement

#955 Add Github CI for linting, testing and building
  .dependabot/config.yml
  .github/workflows/ci.yml
  .travis.yml
  package.json
Labels: enhancement

#975 Add Tabs component
  CHANGELOG.md
  packages/asc-ui/src/components/Tabs/Tab.tsx
  packages/asc-ui/src/components/Tabs/TabButton.tsx
  packages/asc-ui/src/components/Tabs/TabList.tsx
  packages/asc-ui/src/components/Tabs/Tabs.test.tsx
  packages/asc-ui/src/components/Tabs/Tabs.tsx
  packages/asc-ui/src/components/Tabs/index.ts
  packages/asc-ui/src/index.ts
  packages/asc-ui/src/types/KeyboardKeys.ts
  packages/asc-ui/src/utils/hooks/useFocusWithArrows.tsx
  stories/src/ui/Tabs.stories.mdx
  yarn.lock
Labels: design-system-alignment, enhancement, help wanted
