Repository Amsterdam/amsterdam-styled-components, pull requests merged in 2020-09, with the labels that each got.

#1139 Ignore pointer events on Checkbox icon
  packages/asc-ui/src/components/Checkbox/CheckboxStyle.ts
Labels: bug

#1141 Buttons need to be at least 90px width
  CHANGELOG.md
  packages/asc-ui/src/components/Button/ButtonStyle.ts
Labels: bug, design-system-alignment

#1166 Radio button active state had bug on IE11
  CHANGELOG.md
  packages/asc-ui/src/components/Radio/RadioStyle.ts
Labels: bug

#1168 Refactor and export screen-reader only styles
  CHANGELOG.md
  packages/asc-ui/src/components/AmsterdamLogo/AmsterdamLogo.tsx
  packages/asc-ui/src/components/AmsterdamLogo/AmsterdamLogoStyle.ts
  packages/asc-ui/src/components/FormLabelStyle/FormLabelStyle.ts
  packages/asc-ui/src/components/Label/LabelStyle.ts
  packages/asc-ui/src/index.ts
  packages/asc-ui/src/utils/themeUtils.ts
Labels: enhancement

#1178 Export ButtonProps from the package
  CHANGELOG.md
  packages/asc-ui/src/components/Accordion/Accordion.tsx
  packages/asc-ui/src/components/Button/Button.tsx
  packages/asc-ui/src/components/Button/ButtonStyle.ts
  packages/asc-ui/src/components/Button/ShareButton/ShareButtonStyle.ts
  packages/asc-ui/src/components/Button/ToggleButton/ToggleButtonStyle.ts
  packages/asc-ui/src/components/Button/index.ts
  packages/asc-ui/src/components/Menu/MenuButton/MenuButtonStyle.ts
  packages/asc-ui/src/components/ShowMoreShowLess/ShowMoreShowLess.tsx
  packages/asc-ui/src/index.ts
Labels: enhancement
